### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by Poison02** [tychozzz/killbug#1]
大佬你好，你这个项目非常棒，我因为没有做过微服务项目，看了你这个，这个项目太好了，我能借鉴一下吗？整体架构不会变，可能我会加一点其他东西（在我能力范围的），我可以将项目作为我自己的项目吗？如果不可以的话也非常感谢你！

**Comment by tychozzz** [comment]
没问题的，代码完全开源，你可以 fork 仓库或者下载代码，自己改一改。谢谢支持！
如果觉得项目哪里代码写的有问题或文档需要改进，可以帮忙提一下 PR 呀～
